### PR TITLE
Added support for HTTP Authentication

### PR DESCRIPTION
**Pull request by elepedus**

### CODE REVIEW

**Comment by elepedus** [comment]
Oh, I missed that one – yes, it will do, since the whole application is protected.

**Comment by elepedus** [comment]
Tbh, it would be nice to have a separate connection class that can be re-used, rather than re-creating it every time.

**Comment by samjhoward** [comment]
@elepedus I mostly didn't do that because I am a combination of lazy and busy :^)

**Comment by elepedus** [comment]
Lol, yeah - that's the same reason I'm saying 'it would be nice' rather than 'look what I've done' :D

**Comment by elepedus** [comment]
Can this be merged, or is there something else I need to do? Also, once merged, do I need to push it to Rubygems?

**Comment by samjhoward** [comment]
Still waiting on approval from @EthanIDR but you should be able to merge after that. There's a checklist of things to be done after changes are made, I'll ping you a link. 👍

**Comment by elepedus** [comment]
Got the checklist, and gone through it, thanks :) 

I've bumped the version number, but I think someone else might have to publish the gem to rubygems.org once the changes are made

**Pull request merged**
